version: '3.9'

services:
  discord-bot:
    build: .
    image: joramd/flyviking-discord-bot
    container_name: flyviking-discord-bot
    restart: always
    stop_signal: SIGKILL # Skip grace period
    volumes:
      - ./discordBot.log:/app/discordBot.log
      - ./announcement_rss_trackfile:/app/announcement_rss_trackfile
      - ./gallery_rss_trackfile:/app/gallery_rss_trackfile
      - ./aivlasoft_rss_trackfile:/app/aivlasoft_rss_trackfile
      - ./downloads_rss_trackfile:/app/downloads_rss_trackfile
      - ./downloads_update_rss_trackfile:/app/downloads_update_rss_trackfile

networks:
  default:
    name: traefik
    external: true
