version: '3'

services:
  discord-bot:
    build: .
    image: joramd/flyviking-discord-bot
    container_name: flyviking-discord-bot
    restart: always
    stop_signal: SIGKILL # Skip grace period
    volumes:
      - ./discordBot.log:/app/discordBot.log
      - ./announcement_rss_trackfile:/app/announcement_rss_trackfile
      - ./gallery_rss_trackfile:/app/gallery_rss_trackfile
      - ./aivlasoft_rss_trackfile:/app/aivlasoft_rss_trackfile
