version: '3'

services:
  discord-bot:
    build: .
    image: joramd/flyviking-discord-bot
    container_name: flyviking-discord-bot
    restart: always
    stop_signal: SIGKILL # Skip grace period
    volumes:
      - ./live:/app
